const Ninjas ={ 
    theNinja:{
    FixedChakra: true,
    NinjaID: 457,
    Identifier: "a-fn-jounin",
    NinjaName: "a"},
    
    Chakra: {
        "Chakra": 20,
        "Position": 2,
        "Seal": 7,
        "Value": 800,
        "Forbidden": true,
    },
    Stats: {
        "Tai": 43,
        "Nin": 15,
        "Buki": 5,
        "Sta": 35,
        "Ele": 30,
        "Gen": 20,
        
      },
      Growth: {
        "Tai": 6.3,
        "Nin": 1.5,
        "Buki": 0.5,
        "Sta": 2.5,
        "Ele": 2,
        "Gen": 2.5
      },
      Ability: [
        "iron-claw",
        "lightning-body-flicker",
        "lariat",
        "cloak-of-lightning"
      ],
      SealBonus: {
        Low: {
          "Reroll": 35,
          "CritChance": 25
        },
        High: {
          "Crit": 10,
          "End": 30
        }
     
        
    },
    
    }
 
   