let selectedNinja = "";
const Ninjas =[  
{
    "Chakra": 130,
    "Position": 3,
    "Seal": 0,
    "Value": 2500,
    "Stats": {
      "Tai": 40,
      "Nin": 140,
      "Buki": 40,
      "Sta": 50,
      "Ele": 45,
      "Gen": 60
    },
    "Growth": {
      "Tai": 2,
      "Nin": 7,
      "Buki": 1.5,
      "Sta": 2.5,
      "Ele": 2.5,
      "Gen": 4.7
    },
    "Ability": [
      "light-fang",
      "shadow-thunder-blast",
      "limbo",
      "divine-genesis"
    ],
    "NinjaID": 267,
    "Identifier": "madara-rinne-sharingan-kage",
    "NinjaName": "madara"
},
  {
    "Chakra": 10,
    "Position": 1,
    "Seal": -5,
    "Value": 400,
    "Forbidden": true,
    "Stats": {
      "Tai": 2,
      "Nin": 16,
      "Buki": 4,
      "Sta": 25,
      "Ele": 20,
      "Gen": 45
    },
    "Growth": {
      "Tai": 0.5,
      "Nin": 5,
      "Buki": 1,
      "Sta": 2.3,
      "Ele": 1.5,
      "Gen": 3
    },
    "Ability": [
      "hair-camouflage",
      "flower-petal-escape",
      "evil-sealing",
      "string-bean-binding"
    ],
    "FixedChakra": true,
    "NinjaID": 408,
    "Identifier": "kurenai-fn-genin",
    "NinjaName": "kurenai"
  },
    {
      "Chakra": 20,
      "Position": 2,
      "Seal": -1,
      "Value": 800,
      "Forbidden": true,
      "Stats": {
        "Tai": 10,
        "Nin": 30,
        "Buki": 25,
        "Sta": 25,
        "Ele": 25,
        "Gen": 20
      },
      "Growth": {
        "Tai": 0.5,
        "Nin": 4.5,
        "Buki": 4.5,
        "Sta": 2.5,
        "Ele": 2,
        "Gen": 3
      },
      "Ability": [
        "paper-shuriken",
        "paper-chakram",
        "paper-clone",
        "sacred-paper-emissary"
      ],
      "SealBonus": {
        "Low": {
          "Reroll": 35,
          "BukiBoost": 10
        },
        "High": {
          "BukiRec": 15,
          "End": 30
        }
      },
      "FixedChakra": true,
      "NinjaID": 365,
      "Identifier": "konan-fn-jounin",
      "NinjaName": "konan"
      
      
    },
    
  ] 
   
   
    
    
 
   